[package]
name = "astral"
version = "0.1.0"
edition = "2024"

[dependencies]
astral-tokio-tar = "=0.5.3"
futures = "0.3.31"
rustc-hash = "2.1.1"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
