name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: Image to build and push
        options:
          - cve-2021-3156
          - cve-2023-22809
          - cve-2025-32463
          - cve-2025-55182
          - cve-2025-59825
          - cve-2026-24061
          - lecture
          - sudo
          - suid
          - web

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - cve-2021-3156
          - cve-2023-22809
          - cve-2025-32463
          - cve-2025-55182
          - cve-2025-59825
          - cve-2026-24061
          - lecture
          - sudo
          - suid
          - web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 2

      - name: Check if image should be updated
        id: check
        run: |
          if [ "${{ github.event.inputs.image }}" == "${{ matrix.image }}" ]; then
            echo "update=true" >> $GITHUB_OUTPUT
            echo "Manually triggered build and push for ${{ matrix.image }}."
          elif git diff --quiet HEAD~1 -- "${{ matrix.image }}"; then
            echo "update=false" >> $GITHUB_OUTPUT
            echo "No changes detected in ${{ matrix.image }}, skipping."
          else
            echo "update=true" >> $GITHUB_OUTPUT
            echo "Changes detected in ${{ matrix.image }}, building and pushing."
          fi

      - name: Login to Docker Hub
        if: steps.check.outputs.update == 'true'
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        if: steps.check.outputs.update == 'true'
        uses: docker/setup-qemu-action@v3.7.0

      - name: Set up Docker Buildx
        if: steps.check.outputs.update == 'true'
        uses: docker/setup-buildx-action@v3.12.0

      - name: Build and push Docker image
        if: steps.check.outputs.update == 'true'
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ matrix.image }}
          platforms: linux/amd64
          push: true
          tags: pwmcollege/challenge-${{ matrix.image }}:latest
